/* ============================================================
   rekey.mjs — change the practice-mode password.

     node tools/rekey.mjs <old password> <new password>

   Opens js/data/keys.enc.js with the old password and writes it back
   sealed with the new one. The plain answers never touch the disk, and
   the master content is not needed.
   ============================================================ */
import { readFileSync, writeFileSync } from 'node:fs';
import { webcrypto as crypto } from 'node:crypto';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FILE = resolve(REPO, 'js/data/keys.enc.js');
const [oldPw, newPw] = process.argv.slice(2);

if (!oldPw || !newPw) {
  console.error('Usage:  node tools/rekey.mjs "<old password>" "<new password>"');
  process.exit(1);
}

const src = readFileSync(FILE, 'utf8');
const V = JSON.parse(src.slice(src.indexOf('{'), src.lastIndexOf('}') + 1));
const enc = new TextEncoder();
const hexBuf = h => Uint8Array.from(h.match(/../g).map(x => parseInt(x, 16)));

async function keyFrom(pw, salt, use) {
  const base = await crypto.subtle.importKey('raw', enc.encode(pw), 'PBKDF2', false, ['deriveKey']);
  return crypto.subtle.deriveKey(
    { name: 'PBKDF2', salt, iterations: V.iter, hash: 'SHA-256' },
    base, { name: 'AES-GCM', length: 256 }, false, [use]);
}

let plain;
try {
  const k = await keyFrom(oldPw, hexBuf(V.salt), 'decrypt');
  plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: hexBuf(V.iv) }, k,
    Buffer.from(V.ct, 'base64'));
} catch {
  console.error('The old password does not open the answer file. Nothing changed.');
  process.exit(1);
}

const salt = crypto.getRandomValues(new Uint8Array(16));
const iv = crypto.getRandomValues(new Uint8Array(12));
const k2 = await keyFrom(newPw, salt, 'encrypt');
const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, k2, plain);

writeFileSync(FILE,
  '/* GENERATED by tools/build.mjs — do not edit.\n' +
  '   The answer key and explanations, AES-GCM encrypted. Opens only with the\n' +
  '   teacher password, which is typed in the browser and never transmitted. */\n' +
  'window.ANSWER_VAULT = ' + JSON.stringify({
    v: 1, iter: V.iter,
    salt: Buffer.from(salt).toString('hex'),
    iv: Buffer.from(iv).toString('hex'),
    ct: Buffer.from(new Uint8Array(ct)).toString('base64')
  }) + ';\n');

console.log('Password changed. Commit js/data/keys.enc.js and push.');
